site_name: Penetration Testing for Beginners
site_author: dhondta
nav:
  - 'Introduction': index.md
  - 'Penetration Testing Process': slides/proc.md
  - 'Step 1 - Reconnaissance': slides/s1.md
  - 'Step 1 - Reconnaissance':
    - 'Search Engines': labs/s1-search-engines.md
    - 'Website Archives': labs/s1-website-archives.md
    - 'Network Data Search': labs/s1-network-data-search.md
    - 'Whois Information': labs/s1-whois-information.md
    - 'DNS Interrogation': labs/s1-dns-interrogation.md
    - 'Email Addresses Harvesting': labs/s1-email-harvesting.md
    - 'Documents Metadata Search': labs/s1-metadata-search.md
    - 'Website Cloning': labs/s1-website-cloning.md
  - 'Step 2 - Scanning': slides/s2.md
  - 'Step 2 - Scanning':
    - 'Network Scanning': labs/s2-network-scanning.md
    - 'Port Scanning': labs/s2-port-scanning.md
    - 'Service Testing': labs/s2-service-testing.md
    - 'Vulnerability Scanning': labs/s2-vulnerability-scanning.md
  - 'Step 3 - Exploitation': slides/s3.md
  - 'Step 3 - Exploitation':
    - 'Online Password Cracking': labs/s3-online-password-cracking.md
    - 'Vulnerability Exploitation': labs/s3-vulnerability-exploitation.md
    - 'Automated Exploitation': labs/s3-automated-exploitation.md
    - 'Offline Password Cracking': labs/s3-offline-password-cracking.md
    - 'Password Resetting': labs/s3-password-resetting.md
    - 'Social Engineering': labs/s3-social-engineering.md
    - 'Web-Based Exploitation': labs/s3-web-based-exploitation.md
  - 'Step 4 - Maintaining Access': slides/s4.md
  - 'Step 5 - Covering Tracks': slides/s5.md
extra:
  mailto: alexandre.dhondt@gmail.com
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - codehilite
  - pymdownx.details
  - pymdownx.inlinehilite
  - fenced_code
  - fontawesome_markdown
  - nl2br
  - tables
theme:
  name: readthedocs
  custom_dir: mkdocs-revealjs-template/theme
docs_dir: src
site_dir: '/tmp'
#dev_addr: '0.0.0.0:8000'
